keys:
  # People
  # TODO: Add @ruru (I was not able to find a current gpg key @e1mo)
  - &e1mo 0x6D617FD0A85BAADA
  - &leona 0xD5B08ADFC75E3605
  - &n0emis 0xE0262A773B824745

  # Servers
  - &shirley age14ysl953378r2vvy7ft3gwce9xp83pr6wypf5lgx2yjwx2lxra5qs6j8eqe
creation_rules:
  - path_regex: secrets\/all\/*
    key_groups:
      - pgp: [ *e1mo, *leona, *n0emis ]
        age:
        - *shirley
  - path_regex: secrets\/shirley\/*
    key_groups:
      - pgp: [ *e1mo, *leona, *n0emis ]
        age:
        - *shirley
